import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "sonner";

export const metadata = {
  title: "Delmonte",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className="bg-green-900 dark:bg-[#09090b]">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster className="z-50" richColors duration={2000} position="bottom-left" />
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}

